// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web;
        // throw UnsupportedError(
        //   'DefaultFirebaseOptions have not been configured for windows - '
        //   'you can reconfigure this by running the FlutterFire CLI again.',
        // );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGDTYVd_97jGYt4T8se6qp_oUa0xt60Wk',
    appId: '1:144569583555:web:efdc1d5144c17840889f76',
    messagingSenderId: '144569583555',
    projectId: 'my-minecloud',
    authDomain: 'my-minecloud.firebaseapp.com',
    storageBucket: 'my-minecloud.appspot.com',
    measurementId: 'G-PX6CGMQJHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6GFN0R9XZzk73QSvEsA6olAaSt-2J-UM',
    appId: '1:144569583555:android:1579806d9ba0ea25889f76',
    messagingSenderId: '144569583555',
    projectId: 'my-minecloud',
    storageBucket: 'my-minecloud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvzO4M5foR1jyRHxnpMhTZYyVNmu41HSQ',
    appId: '1:144569583555:ios:96c840efa015a2e1889f76',
    messagingSenderId: '144569583555',
    projectId: 'my-minecloud',
    storageBucket: 'my-minecloud.appspot.com',
    iosClientId: '144569583555-h2koa1u4jg0bm3gci832daaoirucuekq.apps.googleusercontent.com',
    iosBundleId: 'com.biton.minecloud.minecloudTal',
  );
}
